baseURL = "https://luraproject.org"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-product-launch"

# The "title" of your website
title = "Lura Project - An Open Source Api Gateway Framework"

googleAnalytics = 'G-77C4WHS94J'

# Render line-breaks in .md-files as line-breaks in HTML.
# This is e.g. useful for rendering a multi-line address.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "Lura Project a Series of LF Projects, LLC"

    copyrightURL = "https://lfprojects.org"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Lura Project - An Open Source Api Gateway Framework"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/share-image.png"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "The Lura Project"

    [params.meta]
        keywords = "api gateway, open source, linux foundation"
