name: Publish Lura site automatically

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: addnab/docker-run-action@v3
      with:
        image: alombarte/hugo
        options: -v ${{ github.workspace }}:/site
        run: npm install && hugo --gc --minify -d docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
